### ISSUE TITLE
to find the initiate of rl value

### ISSUE THREAD

**Issue by JAYON17** [bcosta12/Arduino-MQ6#1]
Hi sir, I just notice a past article that you posted in GitHub which related to MQ6 sensor. #define         RL_VALUE (20)  . About this line of code, may I know the value load resistance RL defined here is fixed or I need to manually adjust the on-board potentiometer or load resistor to get this value?

**Comment by obernardocosta** [comment]
Hi sir @JAYON17 ,

It is a great question. All this kind of sensor as to be calibrated before use.
You always have to take a look at [datasheet](https://www.sparkfun.com/datasheets/Sensors/Biometric/MQ-6.pdf) to get the calibration values.

MQ-6 specifically:

> **SENSITVITY ADJUSTMENT**
> Resistance value of MQ-6 is difference to various kinds and various concentration gases. So, When using this components, sensitivity adjustment is very necessary. we recommend that you calibrate the detector for 1000ppm of LPG concentration in air and use value of Load resistance **( RL) about 20KΩ**(10KΩ to 47KΩ).
> 

This is why the value load resistance RL was defined as 20. Got it?

**Comment by JAYON17** [comment]
Thanks for your reply. So do i need to adjust (by twisting) the on board load resistor to correspond this value (20) or not? If yes, i need to twist it either left hand side or right hand side and until the end of what? Sorry for my bad English .

**Comment by obernardocosta** [comment]
Hi @JAYON17 ,
Are you copping [this](https://github.com/bcosta12/Arduino-MQ6/blob/master/arduinoProject.png) ? 
if yes, just put a 200Ω resitor (red, black, brown, gold). You don't need to use a potentiometer to adjust it, ok?

**Comment by JAYON17** [comment]
Alright, but is  * 20KΩ or  200Ω since the code mentioned there is  20KΩ ,
behind is connect to the GND leg of the sensor right?*

**Comment by obernardocosta** [comment]
@JAYON17 
The 200Ω resistor is this resistor on the board. 
The 20KΩ is just a value for the formula to calibrate the sensor.

So, you can out the 200Ω on the board and run my code, just copy and paste. Try it and tell me the result!

**Comment by JAYON17** [comment]
Ok, currently i dont have the 200 kohm resistor that you mentioned earlier and i just try the code and let it preheat for about 10m. When i use the lighter to test it, the output value seems weird, even the data got negative values some-more
![capture](https://user-images.githubusercontent.com/39524344/40521787-f0619768-5fff-11e8-8a3c-2fa2225290f9.PNG)
.

**Comment by obernardocosta** [comment]
@JAYON17 What the value of the resistor that you use for this test?

**Comment by JAYON17** [comment]
U means the value inside the coding? If yes, is 20KΩ the same as yours

**Comment by obernardocosta** [comment]
@JAYON17  no no, the one on the board.

**Comment by JAYON17** [comment]
Actually the board that i used is this one 
![inked33353464_1803728782998829_2400279732210892800_n_li](https://user-images.githubusercontent.com/39524344/40522085-9f3bd252-6001-11e8-9b07-404f00e3015d.jpg)
People told me the the resistor is already mounted on the break-board and the only things to adjust is the blue box (variable resistor) 
However, i not sure how to twist it to get the value

**Comment by obernardocosta** [comment]
hmm. I don't know how to adjust this variable resistor. Do you know Its range?

**Comment by JAYON17** [comment]
Emm not sure, the provider here doesn't mention also
http://sandboxelectronics.com/?p=191

They said --The protection resistor (10Kohms) and the adjustable (0-50Kohms) are in serial which forms a load resistor RL (10-60Kohms).

**Comment by JAYON17** [comment]
BTW do you mind to show me your sample output? or do you get any negative value before?

**Comment by obernardocosta** [comment]
It's **0-50kΩ**
Try to adjust at **10kΩ**

**Comment by JAYON17** [comment]
Oh after i read deeply, it said the little blue box is only for Digital output . BTW may i know isit the higher the gas position showed in this graph, isit the higher the ppm are? (For example, the CH4 should get a higher ppm than the LPG)?
![image](https://user-images.githubusercontent.com/39524344/40522995-2b5c69fa-6006-11e8-980e-c11bc1a6b35a.png)

**Comment by obernardocosta** [comment]
Yes, It should.

**Comment by JAYON17** [comment]
Alright , Thanks for your help
