### ISSUE TITLE
LPGCurve[3]  =  {3,   0,  -0.4};

### ISSUE THREAD

**Issue by Jackson96** [bcosta12/Arduino-MQ6#2]
Hello, may i know how you get this value LPGCurve[3]  =  {3,   0,  -0.4}; ? 
![image](https://user-images.githubusercontent.com/39672846/40614224-8e5e5e9a-62b4-11e8-8f2a-ea8b83c5d22d.png)
Actually i dont know how to read the 3 and 0 from this graph. Can you point out where do you get this value from? Thanks

**Comment by Jackson96** [comment]
For this (lg1000, lg1), point2: (lg10000, lg0.4)  i know how to get. 
![image](https://user-images.githubusercontent.com/39672846/40615245-958074fc-62b8-11e8-842e-d804bc8b955b.png)
but can you show me the equation to get this? LPGCurve[3] = {3, 0, -0.4};

**Comment by Jackson96** [comment]
ok so based on y2-y1/x2-x1 i able to get the slope but how to get the first 2 values 3, 0?

**Comment by obernardocosta** [comment]
Hi @Jackson96. I don't know if I really can help you. I think the LPG line can be approximated to the point (3,0), but I'm not sure why they choose this point, maybe It can be reletead to this. 

`/*========================  MQGetPercentage ===================
Input:   rs_ro_ratio - Rs divided by Ro
         pcurve      - pointer to the curve of the target gas
Output:  ppm of the target gas
Remarks: By using the slope and a point of the line. The x(logarithmic value of ppm) 
         of the line could be derived if y(rs_ro_ratio) is provided. As it is a 
         logarithmic coordinate, power of 10 is used to convert the result to non-logarithmic 
         value.
===============================================================*/ 
int  MQGetPercentage(float rs_ro_ratio, float *pcurve)
{
  return (pow(10, (((log(rs_ro_ratio)-pcurve[1])/pcurve[2]) + pcurve[0])));
}`

Try to plot this graph to better undertanding.
 I hope I've helped!
